version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: propositions_db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:password@db:5432/propositions_db
    volumes:
      - ./app:/app
    command: [python, app.py]

  crontab:
    build:
      context: ./
      dockerfile: docker/crontab/Dockerfile
    container_name: ingestion-cronjob
    restart: always
    working_dir: /etc/cron.d
    volumes:
      - ./docker/crontab/files:/etc/cron.d
      - ./docker/crontab/scripts:/scriptcron

volumes:
  db: